services:
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    volumes:
      - "./docker-volumes/postgres:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
   
  postgres_admin_portal:
    image: "dpage/pgadmin4"
    ports:
      - "5050:5050"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=admin@gmail.com"
      - "PGADMIN_DEFAULT_PASSWORD=admin"
      - "PGADMIN_LISTEN_PORT=5050"